export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';

export const VOTE_ARTICLE_REQUEST = 'VOTE_ARTICLE_REQUEST';
export const VOTE_ARTICLE_SUCCESS = 'VOTE_ARTICLE_SUCCESS';
export const VOTE_ARTICLE_ERROR = 'VOTE_ARTICLE_ERROR';

